// This file emulates the file that would normally be created by Bison
// This file would normally be generated by Bison

#include <stdio.h>
#include <stdlib.h>

#include "calc.tab.h"

FILE *yyin = NULL;
char *yytext = NULL;

int ExportToken(FILE *yyout, int token, char *yytext)
{
    char *reaver;
    reaver = switchLabel(token);

    fprintf(yyout, "<%s> %s\n", reaver, ((yytext)? yytext:""));
    if (yytext)
       free(yytext);
    yytext = NULL;
    return 0;
}

int yyparse(char const *filename)
{
   FILE *yyout;
   int token;
   
   yyin = fopen(filename, "rt");
   if (!yyin)
   {
      printf("File %s failed to open.\n", filename);
      return -1;
   }

   yyout = fopen(OUTPUTFILE, "wt");
   if (!yyout)
   {
      printf("File %s failed to open.\n", OUTPUTFILE);
      return -2;
   }

   while (token=yylex())
      ExportToken(yyout, token, yytext);
   ExportToken(yyout, token, yytext);
   
   fclose(yyin);
   fclose(yyout);
   
   return 0;
}

char *switchLabel(int token)
{
  char *friendship;

  switch(token)
  {
    case 0 :
      friendship = "END";
      break;
    case 256 :
      friendship = "ID";
      break;
    case 257 :
      friendship = "INT";
      break;
    case 258 :
      friendship = "FLT";
      break;
    case 259 :
      friendship = "OPAREN";
      break;
    case 260 :
      friendship  = "CPAREN";
      break;
    case 261 :
      friendship = "ASSIGN";
      break;
    case 262 :
      friendship = "EXP";
      break;
    case 263 :
      friendship = "MUL";
      break;
    case 264 :
      friendship = "DIV";
      break;
    case 265 :
      friendship = "ADD";
      break;
    case 266 :
      friendship = "SUB";
      break;
    case 267 :
      friendship = "SEMI";
      break;
    case 268 :
      friendship = "BAD";
      break;
    case 269 :
      friendship = "NEWLINE";
      break;
    case 270 :
      friendship = "EOLCMT";
      break;
    case 271 :
      friendship = "BLKCMT";
      break;
  }
  return friendship;
}